# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Conta de WhatsApp

# Model Form Field configuration
form: $/getbyte/whatsapp/models/account/fields.yaml

# Model Class name
modelClass: GetByte\Whatsapp\Models\Account

# Default redirect location
defaultRedirect: getbyte/whatsapp/accounts

redirect: getbyte/whatsapp/accounts

# Update page
update:
    title: backend::lang.form.update_title
    redirect: getbyte/whatsapp/accounts
    redirectClose: getbyte/whatsapp/accounts

# Preview page
preview:
    title: backend::lang.form.preview_title
